"""tmp

Revision ID: 08baa2c32e92
Revises: 30db8f4269d2
Create Date: 2024-08-09 02:10:54.009411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08baa2c32e92' 
down_revision: str = '30db8f4269d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

 
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tusers', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_primary_key("pk_tvotes", "tvotes", ["user_id", "post_id"]) 
    op.create_foreign_key("tvotes_tposts_fk",source_table="tvotes",referent_table="tposts",local_cols=["post_id"],remote_cols=["id"],ondelete="Cascade")
    op.create_foreign_key("tvotes_tusers_fk",source_table="tvotes",referent_table="tusers",local_cols=["user_id"],remote_cols=["id"],ondelete="Cascade")
    op.create_foreign_key("tposts_tusers_fk",source_table="tposts",referent_table="tusers",local_cols=["owner_id"],remote_cols=["id"],ondelete="Cascade") 
    # ### end Alembic commands ###()'user_id', 'post_id')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tusers', 'phone_number')
    op.drop_constraint("pk_tvotes",table_name="tvotes")
    op.drop_constraint("tvotes_tposts_fk",table_name="tvotes")
    op.drop_constraint("tvotes_tusers_fk",table_name="tvotes") 
    op.drop_constraint("tposts_tusers_fk",table_name="tposts") 
    # ### end Alembic commands ###
    
