"""Added tpost tvote tuser table

Revision ID: 757594cd56ee
Revises: 2dd5e9ae1164
Create Date: 2024-08-09 03:13:27.200201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757594cd56ee'
down_revision: Union[str, None] = '2dd5e9ae1164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
